# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- reality-blue-jekyll-theme.gemspec
- .jekyll-cache

# SASS Configuration
sass:
    sass_dir: _sass

# Plugins and plugin settings
plugins:
- jekyll-paginate
paginate: 5

# Site Settings
title: Reality Blue
author: Terry Wen
sections:
    - name: about
      file: _about.html
    - name: links
      file: _links.html
    - name: blog
      file: _blog.html