# Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- Gemfile
- Gemfile.lock
- reality-blue-jekyll-theme.gemspec
- .jekyll-cache

# SASS Configuration
sass:
    sass_dir: _sass

# Plugins and plugin settings
plugins:
- jekyll-paginate
paginate: 5

# Site Settings
title: Reality Blue
author: Terry Wen
url: https://t-wen.space/reality-blue
sections:
    - name: section 1
      file: _section-1.html
    - name: section 2
      file: _section-2.html
    - name: blog
      file: _blog.html